// import type { Metadata } from "next";
// import { Inter, Poppins } from "next/font/google";
// import "./globals.css";
// import React from "react";
// import Navbar from "@/components/shared/Navbar";

// const inter = Inter({
//   subsets: ["latin"],
//   weight: [
//     "100",
//     "200",
//     "300",
//     "400",
//     "500",
//     "600",
//     "700",
//     "700",
//     "800",
//     "900",
//   ],
//   variable: "--font-inter",
// });

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600", "700"],
//   variable: "--font-poppins",
// });

// export const metadata: Metadata = {
//   title: "Days-Shop",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={`${inter.variable} ${poppins.variable}`}>
//         {/* <Navbar /> */}
//         {children}
//       </body>
//     </html>
//   );
// }


// Providers
// import { ThemeProvider } from "@/context/ThemeProvider";
import type { Metadata } from "next";
import React from "react";
import {  Poppins } from "next/font/google";
import "./globals.css";
// import { Toaster } from "@/components/ui/toaster";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {/* <ThemeProvider defaultTheme="light"> */}
          {children}
          {/* <Toaster /> */}
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}